### ISSUE TITLE
fails to submit file "irx _file.irx" for analysis using jenkins plugin.

### ISSUE THREAD

**Issue by giovannabarbosamg** [HCL-TECH-SOFTWARE/appscan-gradle-plugin#21]
I have a pipeline where one stage is for doing checks on the files inside my container, because the plugin's client takes a long time to download, I used an image with the command line interface of appscan to generate the IRX file with it as well, using the command "appscan.sh prepare -n irx_file.irx". I want to send this file for analysis using the appscan plugin in jenkins, but I get the following message

`Failed to run the security scan: The scan target /home/jenkins/agent/workspace/build_dummy-spring-simple_master/irx_file.irx is invalid.`

besides that, the client downloads it anyway and generates the file anyway. is there a way for me to use the plugin without it downloading from the client and without it generating a new file? thanks.

**Comment by mattmurp** [comment]
Hi.  When you specify an existing irx file in the "Target" field, the Jenkins plugin won't download a new SAClientUtil.  It will just upload the existing irx file.  I just ran a quick test to confirm this and it's working as expected.
Can you verify that the file /home/jenkins/agent/workspace/build_dummy-spring-simple_master/irx_file.irx exists and the user account that Jenkins is running under has permissions to access it?

**Comment by mattmurp** [comment]
Since this question is specific to the Jenkins plugin, it would be best to address in that repository (https://github.com/jenkinsci/appscan-plugin).  I'll close this issue, but please reopen it or open a new issue if you have problems with the Gradle plugin.
